<meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
    <meta content="" name="description">

      <!-- Favicons -->
      <link rel="icon" href="img/logo2.png">


        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Ruda:400,900,700" rel="stylesheet">

          <!-- Bootstrap CSS File -->
          <link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">

            <!-- Libraries CSS Files -->
            <link href="lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
              <link href="lib/prettyphoto/css/prettyphoto.css" rel="stylesheet">
                <link href="lib/hover/hoverex-all.css" rel="stylesheet">
                  <link href="lib/jetmenu/jetmenu.css" rel="stylesheet">
                    <link href="lib/owl-carousel/owl-carousel.css" rel="stylesheet">

                      <!-- Main Stylesheet File -->
                      <link href="css/style.css" rel="stylesheet">
                        <link rel="stylesheet" href="css/colors/blue.css">

                          </head>
                          <body>


                            <div class="topbar clearfix">
                              <div class="container-fluid">
                                <div class="col-lg-1 text-left">
                                  <img src="img/flag.png"></img>
                                </div>

                                <div class="col-lg-11 text-right">
                                  <div class="social_buttons">
                                    <a href="https://www.facebook.com/gstsystemsindia/" data-toggle="tooltip" data-placement="bottom" title="Facebook" target="_blank">
                                      <i class="fa fa-facebook"></i>
                                    </a>
                                    <a href="https://twitter.com/askGSTech" data-toggle="tooltip" data-placement="bottom" title="Twitter" target="_blank">
                                      <i class="fa fa-twitter"></i>
                                    </a>
                                    <a href="https://www.youtube.com/channel/UCFYpOk92qurlO5t-Z_y-bOQ" data-toggle="tooltip" data-placement="bottom" title="YouTube" target="_blank">
                                      <i class="fa fa-youtube"></i>
                                    </a>
                                    <a href="https://www.linkedin.com/authwall?trk=bf&trkInfo=AQG8JXzec-7ZygAAAWzmMrqg8TtX9D9abw9-TErmL9xKN-3E1c-2pToVmfhLLa2l9gvwsi6VPT8uWc7ZAWrH5DInYvZwuhLIMHJ0rhbSSoltYvhFVoUmmfdE6hc1a3Gmw187lE4=&originalReferer=&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2F13204281%3Ftrk%3Dtyah%26trkInfo%3DclickedVertical%253Acompany%252CclickedEntityId%253A13204281%252Cidx%253A4-2-9%252CtarId%253A1478268606810%252Ctas%253AGoods%2520and%2520Services%2520" data-toggle="tooltip" data-placement="bottom" title="Linkedin" target="_blank">
                                      <i class="fa fa-linkedin"></i>
                                    </a>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <!-- end container -->
                            </div>
                            <!-- end topbar -->

                            <header class="header">
                              <div class="container-fluid">
                                <div class="site-header clearfix">
                                  <div class="col-lg-3 col-md-3 col-sm-12 title-area">
                                    <div class="site-title" id="title">
                                      <a href="home.aspx" title="GST">
                                        <img src="img/logo.png" alt="Goods And Services Tax">
            </a>
                                    </div>
                                  </div>
                                  <!-- title area -->
                                  <div class="col-lg-9 col-md-12 col-sm-12">
                                    <div id="nav" class="right">
                                      <div class="container clearfix">
                                        <ul id="jetmenu" class="jetmenu blue">
                                          <li>
                                            <asp:HyperLink ID="HyperLink3" class="active" runat="server" NavigateUrl="~/home.aspx">Home</asp:HyperLink>
                                          </li>
                                          <li>
                                            <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="~/send.aspx">Message</asp:HyperLink>
                                          </li>
                                          <li>
                                            <asp:HyperLink ID="HyperLink2" runat="server" NavigateUrl="~/inbox.aspx">Inbox</asp:HyperLink>
                                          </li>
                                          <li>
                                            <asp:HyperLink ID="HyperLink5" runat="server" NavigateUrl="~/sendm.aspx">Sent</asp:HyperLink>
                                          </li>
                                          <li>
                                            <asp:HyperLink ID="HyperLink7" runat="server" NavigateUrl="~/myinfo.aspx">My Info</asp:HyperLink>
                                          </li>
                                          <li>
                                            <asp:HyperLink ID="HyperLink6" runat="server" NavigateUrl="~/cal.aspx">Pay GST</asp:HyperLink>
                                          </li>
										   <li>
                                            <asp:HyperLink ID="HyperLink8" runat="server" NavigateUrl="~/paid.aspx">Paid GST</asp:HyperLink>
                                          </li>
										  <li>
                                            <asp:HyperLink ID="HyperLink9" runat="server" NavigateUrl="~/settings.aspx">Settings</asp:HyperLink>
                        <ul class="dropdown">
                       
                          <li>
                            <a href="#">Name</a>
                            <ul class="dropdown">
                              <li>
                                <a href="fname.aspx" target="_blank">First Name</a>
                              </li>
                              <li>
                                <a href="mname.aspx" target="_blank"> Middle Name</a>
                              </li>
                              <li>
                                <a href="lname.aspx" target="_blank">Last Name</a>
                              </li>
                            </ul>
                          </li>

                          <li>
                            <a href="#">Address</a>
                            <ul class="dropdown">
                              <li>
                                <a href="hno.aspx" target="_blank">Home/Plot NO</a>
                              </li>
                              <li>
                                <a href="st.aspx" target="_blank">Street</a>
                              </li>
                              <li>
                                <a href="ar.aspx" target="_blank">Area</a>
                              </li>

                              <li>
                                <a href="city.aspx" target="_blank">City</a>
                              </li>
                              <li>
                                <a href="state.aspx" target="_blank">State</a>
                              </li>
                            </ul>
                          </li>


                          <li>
                            <a href="#">Document</a>
                            <ul class="dropdown">
                              <li>
                                <a href="acard.aspx" target="_blank">Aadhar Card</a>
                              </li>
                              <li>
                                <a href="pcard.aspx" target="_blank">PAN Card</a>
                              </li>
                             </ul>
                          </li>


                          <li>
                            <a href="#">Contact</a>
                            <ul class="dropdown">
                              <li>
                                <a href="mobile.aspx" target="_blank">Mobile Number</a>
                              </li>
                              <li>
                                <a href="email.aspx" target="_blank">Email ID</a>
                              </li>
                            </ul>
                          </li>


                          <li>
                            <a href="pwd.aspx" target="_blank">Password</a>
                                                    </li>
                          <li>
                            <a href="dob.aspx" target="_blank">Birth Date</a>
                          </li>
                          
                        </ul>
                      </li>
										  <li>
                                            <a href="#">Help</a>
                                            <ul class="dropdown">
                                             
                                             <li>
                                                <a href="mygst1.aspx" target="_blank">My GST</a>
                                              </li>
                                              <li>
                                                <a href="#">Video</a>
                                                <ul class="dropdown">

                                                  <li>
                                                    <a href="img/gst2.mp4" target="_blank">GST-1</a>
                                                  </li>
                                                  <li>
                                                    <a href="img/gst3.mp4" target="_blank">GST-2</a>
                                                  </li>
                                                  <li>
                                                    <a href="img/gst4.mp4" target="_blank">GST-3</a>
                                                  </li>

                                                  <li>
                                                    <a href="img/gst6.mp4" target="_blank">GST-4</a>
                                                  </li>

                                                  <li>
                                                    <a href="img/gst1.mp4" target="_blank">GST-5 (Hindi)</a>
                                                  </li>
                                                  <li>
                                                    <a href="img/gst6.mp4" target="_blank">GST-6 (Hindi)</a>
                                                  </li>
                                                </ul>
                                              </li>

                                              <li>
                                                <a href="#" target="_blank">Book</a>
                                                <ul class="dropdown">

                                                  <li>
                                                    <a href="img/gst.pdf" target="_blank">GST (Pdf File)</a>
                                                  </li>
                                                  <li>
                                                    <a href="img/gstbook.docx" target="_blank">GST (Word File)</a>
                                                  </li>
                                                </ul>
                                              </li>



                                              <li>
                                                <a href="send.aspx">Feedbak</a>
                                              </li>
                                              </ul>
                                          </li>
                                          
                                         
										  <li>
                                            <asp:HyperLink ID="HyperLink10" runat="server" NavigateUrl="~/logout.aspx">log out</asp:HyperLink>
                                          </li>
                                          
                                        </ul>
                                      </div>
                                    </div>
                                    <!-- nav -->
                                  </div>
                                  <!-- title area -->
                                </div>
                                <!-- site header -->
                              </div>
                              <!-- end container -->
                            </header>
                            <!-- end header -->